host: irc.spi.gt
port: 6697
modes: B
nickname: Dumbo
channels:
  - '#hell'
  - '#paper'
  - '#spigot'
commands:
  randomquote:
    - 'quote'
    - 'dumbo'
    - 'dumball'
    - 'dum'
  sendline:
    - 'sendline'
ops:
  - 'Sweepyoface'
  - 'LaxWasHere'