host: irc.spi.gt
port: 6697
modes: B
nickname: Dumbo
channels:
  - '#hell'
  - '#paper'
  - '#spigot'
commands:
  randomquote:
    - 'quote'
    - 'dumbo'
    - 'dumball'
    - 'dum'
  sendline:
    - 'sendline'
  tacos:
    - 'tacos'
ops:
  - 'Sweepyoface'
  - 'LaxWasHere'
  - 'Spottedleaf'
blocked:
  - 'qball@SpigotMC-a31605.qballs.kelp.in'